version: "3.3"
services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: career-portal-web
    depends_on:
      - database
    volumes:
      - ./src:/var/www/html
    ports:
      - 8000:80

  database:
    container_name: career-portal-db
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
      MYSQL_DATABASE: test_db
    ports:
      - 8001:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: